spring.application.name=mytechseller
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/sistemacompras?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sua senha no mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (para o Hibernate criar tabelas automaticamente)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
=======
spring.datasource.url=jdbc:mysql://localhost:3306/SistemaCompras?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

JPA (para o Hibernate criar tabelas automaticamente)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
>>>>>>> 4b35fa2 (aprimorando as classes do pacote modelos)
